In [1]:
import pandas as pd

In [8]:
d2015=pd.read_csv('DEVICE2015.txt',sep='|',encoding='latin1',on_bad_lines='skip')

#when encountering lines with incorrect column numbers, skip

/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/74819253.py:1: DtypeWarning: Columns (32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  d2015=pd.read_csv('DEVICE2015.txt',sep='|',encoding='latin1',on_bad_lines='skip')

In [19]:
dfs = {} #Save all years inside one dictionary
def load_device_year(year):
    path = f"DEVICE{year}.txt"
    dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
    #when encountering lines with incorrect column numbers, skip

In [20]:
for year in range(2015,2026):
    load_device_year(year)

/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (0,1,2,4,5,6,17,25,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (0,1,2,3,4,5,6,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (0,1,2,3,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (0,1,2,3,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (0,1,2,3,4,5,6,25,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (0,1,2,3,4,5,6,16,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (0,1,2,3,4,5,6,25,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')
/var/folders/4l/g3wrn7zd5dz5cnt59_md7ldm0000gn/T/ipykernel_56776/2884843464.py:4: DtypeWarning: Columns (0,1,2,4,5,6,25,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs[f"d{year}"] = pd.read_csv(path,sep='|',encoding='latin1',on_bad_lines='skip')

In [24]:
dfs["d2015"].head()

,MDR_REPORT_KEY,DEVICE_EVENT_KEY,IMPLANT_FLAG,DATE_REMOVED_FLAG,DEVICE_SEQUENCE_NO,IMPLANT_DATE_YEAR,DATE_REMOVED_YEAR,SERVICED_BY_3RD_PARTY_FLAG,DATE_RECEIVED,BRAND_NAME,...,LOT_NUMBER,OTHER_ID_NUMBER,DEVICE_AVAILABILITY,DATE_RETURNED_TO_MANUFACTURER,DEVICE_REPORT_PRODUCT_CODE,DEVICE_AGE_TEXT,DEVICE_EVALUATED_BY_MANUFACTUR,COMBINATION_PRODUCT_FLAG,UDI-DI,UDI-PUBLIC
0,2296019,NaN,NaN,NaN,451705,2008.0,2010.0,NaN,2015/07/13,NEXGEN LCCK FEMORAL IMPLANT,...,60780124,NaN,N,NaN,JWH,DA,NaN,N,NaN,NaN
1,2686192,NaN,NaN,NaN,20222,2010.0,2010.0,NaN,2015/01/09,G2 FILTER SYSTEM - FEMORAL,...,GFSL1260,NaN,N,NaN,DTK,DA,NaN,N,NaN,NaN
2,2893201,NaN,NaN,NaN,309162,NaN,NaN,NaN,2015/05/11,OLYMPUS EVIS EXERA II DUODENOVIDEOSCOPE,...,NaN,NaN,Y,2012/12/11,FDT,DA,NaN,N,NaN,NaN
3,4068041,NaN,NaN,NaN,110085,2006.0,2014.0,NaN,2015/02/13,CORMET RESURFACING,...,JGFL,NaN,NaN,NaN,NXT,NaN,NaN,N,NaN,NaN
4,4080233,NaN,NaN,NaN,271555,NaN,NaN,NaN,2015/04/24,MAXCORE DISPOSABLE CORE BIOPSY INSTRUMENT,...,REYA2017,NaN,R,2014/08/27,KNW,DA,NaN,N,NaN,NaN

In [25]:
combined_df = pd.concat(dfs.values(), ignore_index=True)

In [26]:
combined_df.head()

,MDR_REPORT_KEY,DEVICE_EVENT_KEY,IMPLANT_FLAG,DATE_REMOVED_FLAG,DEVICE_SEQUENCE_NO,IMPLANT_DATE_YEAR,DATE_REMOVED_YEAR,SERVICED_BY_3RD_PARTY_FLAG,DATE_RECEIVED,BRAND_NAME,...,LOT_NUMBER,OTHER_ID_NUMBER,DEVICE_AVAILABILITY,DATE_RETURNED_TO_MANUFACTURER,DEVICE_REPORT_PRODUCT_CODE,DEVICE_AGE_TEXT,DEVICE_EVALUATED_BY_MANUFACTUR,COMBINATION_PRODUCT_FLAG,UDI-DI,UDI-PUBLIC
0,2296019,NaN,NaN,NaN,451705,2008.0,2010.0,NaN,2015/07/13,NEXGEN LCCK FEMORAL IMPLANT,...,60780124,NaN,N,NaN,JWH,DA,NaN,N,NaN,NaN
1,2686192,NaN,NaN,NaN,20222,2010.0,2010.0,NaN,2015/01/09,G2 FILTER SYSTEM - FEMORAL,...,GFSL1260,NaN,N,NaN,DTK,DA,NaN,N,NaN,NaN
2,2893201,NaN,NaN,NaN,309162,NaN,NaN,NaN,2015/05/11,OLYMPUS EVIS EXERA II DUODENOVIDEOSCOPE,...,NaN,NaN,Y,2012/12/11,FDT,DA,NaN,N,NaN,NaN
3,4068041,NaN,NaN,NaN,110085,2006.0,2014.0,NaN,2015/02/13,CORMET RESURFACING,...,JGFL,NaN,NaN,NaN,NXT,NaN,NaN,N,NaN,NaN
4,4080233,NaN,NaN,NaN,271555,NaN,NaN,NaN,2015/04/24,MAXCORE DISPOSABLE CORE BIOPSY INSTRUMENT,...,REYA2017,NaN,R,2014/08/27,KNW,DA,NaN,N,NaN,NaN

In [29]:
#Decribe Dataset
combined_df.describe()

,MDR_REPORT_KEY,DEVICE_EVENT_KEY,IMPLANT_FLAG,DATE_REMOVED_FLAG,DEVICE_SEQUENCE_NO,IMPLANT_DATE_YEAR,DATE_REMOVED_YEAR,SERVICED_BY_3RD_PARTY_FLAG,DATE_RECEIVED,BRAND_NAME,...,LOT_NUMBER,OTHER_ID_NUMBER,DEVICE_AVAILABILITY,DATE_RETURNED_TO_MANUFACTURER,DEVICE_REPORT_PRODUCT_CODE,DEVICE_AGE_TEXT,DEVICE_EVALUATED_BY_MANUFACTUR,COMBINATION_PRODUCT_FLAG,UDI-DI,UDI-PUBLIC
count,19414644,167,175,99,19414493,5966462.0,4659963.0,9352705,19414513,19319969,...,10392327,486561,19405705,5514681,19414243,7898579,11636215,19382266,11674709,11689792
unique,19380178,43,29,6,3114215,167.0,113.0,11,3975,350117,...,2783499,50097,6,5693,3793,9586,5,4,188651,1001570
top,VIDEOSCOPE,SMALL INTESTINAL VIDEOSCOPE,"AIZU OLYMPUS CO., LTD.",3-1-1 NIIDERAKITA,24193,2024.0,2024.0,N,2025/06/17,DEXCOM G6 CONTINUOUS GLUCOSE MONITORING SYSTEM,...,NI,1-1960Z86,N,2025/01/14,DZE,DA,Y,N,10885403222054,10885403222054
freq,56,46,39,39,35,570962.0,699941.0,5939442,40264,1301813,...,412398,49451,10544991,6189,3386753,6806555,3911406,18197247,643655,648945

In [30]:
#Check columns with NAN
combined_df.isna().any()

MDR_REPORT_KEY                    False
DEVICE_EVENT_KEY                   True
IMPLANT_FLAG                       True
DATE_REMOVED_FLAG                  True
DEVICE_SEQUENCE_NO                 True
IMPLANT_DATE_YEAR                  True
DATE_REMOVED_YEAR                  True
SERVICED_BY_3RD_PARTY_FLAG         True
DATE_RECEIVED                      True
BRAND_NAME                         True
GENERIC_NAME                       True
MANUFACTURER_D_NAME                True
MANUFACTURER_D_ADDRESS_1           True
MANUFACTURER_D_ADDRESS_2           True
MANUFACTURER_D_CITY                True
MANUFACTURER_D_STATE_CODE          True
MANUFACTURER_D_ZIP_CODE            True
MANUFACTURER_D_ZIP_CODE_EXT        True
MANUFACTURER_D_COUNTRY_CODE        True
MANUFACTURER_D_POSTAL_CODE         True
DEVICE_OPERATOR                    True
EXPIRATION_DATE_OF_DEVICE          True
MODEL_NUMBER                       True
CATALOG_NUMBER                     True
LOT_NUMBER                         True
OTHER_ID_NUMBER                    True
DEVICE_AVAILABILITY                True
DATE_RETURNED_TO_MANUFACTURER      True
DEVICE_REPORT_PRODUCT_CODE         True
DEVICE_AGE_TEXT                    True
DEVICE_EVALUATED_BY_MANUFACTUR     True
COMBINATION_PRODUCT_FLAG           True
UDI-DI                             True
UDI-PUBLIC                         True
dtype: bool

In [31]:
#Check numbers of NAN per Column
combined_df.isna().sum()

MDR_REPORT_KEY                           0
DEVICE_EVENT_KEY                  19414477
IMPLANT_FLAG                      19414469
DATE_REMOVED_FLAG                 19414545
DEVICE_SEQUENCE_NO                     151
IMPLANT_DATE_YEAR                 13448182
DATE_REMOVED_YEAR                 14754681
SERVICED_BY_3RD_PARTY_FLAG        10061939
DATE_RECEIVED                          131
BRAND_NAME                           94675
GENERIC_NAME                         75404
MANUFACTURER_D_NAME                  93540
MANUFACTURER_D_ADDRESS_1            590796
MANUFACTURER_D_ADDRESS_2          17553798
MANUFACTURER_D_CITY                 390870
MANUFACTURER_D_STATE_CODE          6975186
MANUFACTURER_D_ZIP_CODE            1318761
MANUFACTURER_D_ZIP_CODE_EXT       13951641
MANUFACTURER_D_COUNTRY_CODE        1710497
MANUFACTURER_D_POSTAL_CODE         1318627
DEVICE_OPERATOR                    1054088
EXPIRATION_DATE_OF_DEVICE         13582861
MODEL_NUMBER                       5936189
CATALOG_NUMBER                     2663549
LOT_NUMBER                         9022317
OTHER_ID_NUMBER                   18928083
DEVICE_AVAILABILITY                   8939
DATE_RETURNED_TO_MANUFACTURER     13899963
DEVICE_REPORT_PRODUCT_CODE             401
DEVICE_AGE_TEXT                   11516065
DEVICE_EVALUATED_BY_MANUFACTUR     7778429
COMBINATION_PRODUCT_FLAG             32378
UDI-DI                             7739935
UDI-PUBLIC                         7724852
dtype: int64