Import JSON Device Recall Data

In [36]:
import pandas as pd
import json
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

DataFrame shape: (57511, 35)
Columns: Index(['cfres_id', 'product_res_number', 'event_date_initiated',
       'event_date_posted', 'recall_status', 'res_event_number',
       'product_code', 'product_description', 'code_info', 'recalling_firm',
       'address_1', 'city', 'state', 'postal_code', 'additional_info_contact',
       'reason_for_recall', 'root_cause_description', 'action',
       'product_quantity', 'distribution_pattern', 'openfda.k_number',
       'openfda.registration_number', 'openfda.fei_number',
       'openfda.device_name', 'openfda.medical_specialty_description',
       'openfda.regulation_number', 'openfda.device_class', 'address_2',
       'event_date_terminated', 'firm_fei_number',
       'other_submission_description', 'k_numbers', 'pma_numbers',
       'event_date_created', 'openfda.pma_number'],
      dtype='object')

In [ ]:
json_path = "/projectnb/sparkgrp/dd4g-muckrock-patient-safety/device-recall-0001-of-0001.json"

# Load JSON
with open(json_path, 'r') as f:
    data = json.load(f)

#print(type(data)) 
#print(list(data.keys())

df = pd.json_normalize(data['results'])
#print("DataFrame shape:", df.shape)
#print("Columns:", df.columns)

In [37]:
df.head()

,cfres_id,product_res_number,event_date_initiated,event_date_posted,recall_status,res_event_number,product_code,product_description,code_info,recalling_firm,...,openfda.regulation_number,openfda.device_class,address_2,event_date_terminated,firm_fei_number,other_submission_description,k_numbers,pma_numbers,event_date_created,openfda.pma_number
0,218307,Z-1472-2026,2026-01-21,2026-02-26,"Open, Classified",98332,FNM,"Adapt Pump, Model/Catalog Number: 61600200-Ada...",UDI-DI 0084569904914; All serial numbers with ...,Agiliti Health Ellis,...,880.5550,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,218406,Z-1462-2026,2026-01-14,2026-02-24,"Open, Classified",98303,KPL,"PIE PAK\nModels: P2HC-A, P2HC-S, P2HC",All Lots\nUDI:,Edermy LLC,...,876.5220,2,Ste A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,105069,Z-0389-2012,2011-09-19,2012-01-11,Terminated,60344,LFQO,Magnus Hybrid operating table columns 1180.01A...,"510 k EXEMPT 1180.01A1- Lot #0002, 0004, 0005...",Maquet Inc.,...,NaN,NaN,NaN,2011-12-08,NaN,NaN,NaN,NaN,NaN,NaN
3,105700,Z-0485-2012,2011-11-28,2012-01-11,Terminated,60528,RER,Raymond Laser alignment guide - Model #1096597...,Model #1096597/002,The Raymond Corporation S Canal,...,,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,131624,Z-0604-2015,2014-11-17,2014-12-12,Terminated,69838,KOG,"PKG, OBTURATOR, 5.5MM FOR HASSON CANNULA, P/N ...",37302 37858 39543 45622 48347 48903 49147 4914...,Stryker Endoscopy,...,NaN,NaN,NaN,2015-07-17,2936485,NaN,NaN,NaN,NaN,NaN

Identify Unique Product Codes and IDs

In [39]:
print(df['product_code'].unique()[:10])
print(df['cfres_id'].unique()[:10])

['FNM' 'KPL' 'LFQO' 'RER' 'KOG' 'N/A' 'RCE' 'REM' 'RHP' 'MIE']
['218307' '218406' '105069' '105700' '131624' '131797' '131743' '131693'
 '131625' '131848']

Basic EDA (explore how many rows contain issues involving batteries, for instance)

In [40]:
battery_rows = df[df['reason_for_recall'].str.contains("battery", case=False, na=False)]

print(battery_rows.shape)
print(battery_rows.head())

(920, 35)
    cfres_id product_res_number event_date_initiated event_date_posted  \
124   181608        Z-0518-2021           2020-04-30               NaN
143   172735        Z-1773-2019           2019-05-10               NaN
495   103146        Z-0142-2012           2011-09-23        2011-10-31
621   112481        Z-0049-2013           2012-09-25        2012-10-11
862    64398        Z-0051-2008           2007-03-16        2007-11-24

        recall_status res_event_number product_code  \
124  Open, Classified            85711          N/A
143        Terminated            82803          LPA
495        Terminated            59582          DRY
621        Terminated            63079          KFM
862        Terminated            44793          LWP

                                   product_description  \
124  MiniMed 640G, insulin pump, Ref/Model # MMT-17...
143  CardioCommand, Inc. Transesophageal Cardiac Pa...
495  CDI Blood Parameter Monitoring System 500 incl...
621  Battery, 100/115V (Includes charger and connec...
862  Guidant VITALITY 2 DR/VR (Models T165, T175) a...

                                             code_info  \
124  All serial numbers expiration date- 3 years fr...
143      Serial Numbers:  8059, 8060, 8022, 8063, 8211
495  Catalog # 500AVHCT, CDI Blood Parameter Monito...
621  Catalog number: 9490; and lot numbers: 0101,10...
862  Model T165:  T165/100104, T165/100106, T165/10...

                                recalling_firm  ... openfda.regulation_number  \
124                             Medtronic Inc.  ...                       NaN
143                         Cardiocommand Inc.  ...
495  Terumo Cardiovascular Systems Corporation  ...                  870.4330
621  Terumo Cardiovascular Systems Corporation  ...                  870.4360
862                 Boston Scientific CRM Corp  ...

    openfda.device_class address_2 event_date_terminated firm_fei_number  \
124                  NaN       NaN                   NaN      3003166194
143                    3   Ste 110            2021-04-12         1927197
495                    2       NaN            2013-04-11             NaN
621                    2       NaN            2014-01-15             NaN
862                    3       NaN            2007-11-23             NaN

    other_submission_description  k_numbers pma_numbers event_date_created  \
124                          NaN        NaN       [PMA]         2020-12-02
143                          NaN        NaN   [P860008]         2019-06-12
495                          NaN  [K972962]         NaN                NaN
621                          NaN  [K882758]         NaN                NaN
862                          NaN        NaN   [P960040]                NaN

                                    openfda.pma_number
124                                                NaN
143                                 [P840002, P860008]
495                                                NaN
621                                                NaN
862  [P950029, P860027, P030035, P780009, P840068, ...

[5 rows x 35 columns]

In [41]:
#account for nulls 
df['reason_for_recall'] = df['reason_for_recall'].fillna('')

#how many rows contain batteries
battery_count = df['reason_for_recall'].str.contains('battery', case=False).sum()
print(f"Rows containing 'battery': {battery_count}")

Rows containing 'battery': 920

In [42]:
vectorizer = CountVectorizer(ngram_range=(2,2), stop_words='english')
X = vectorizer.fit_transform(df['reason_for_recall'])

#sum columns directly on sparse matrix
sums = X.sum(axis=0)  
sums_array = sums.A1 

bigrams = Counter(dict(zip(vectorizer.get_feature_names_out(), sums_array)))
print(bigrams.most_common(20))

[('instructions use', np.int64(1165)), ('sterile barrier', np.int64(1099)), ('recall initiated', np.int64(1010)), ('expiration date', np.int64(961)), ('kits contain', np.int64(768)), ('compromising sterility', np.int64(756)), ('package integrity', np.int64(719)), ('shelf life', np.int64(690)), ('non sterile', np.int64(666)), ('use ifu', np.int64(634)), ('specific lots', np.int64(617)), ('received complaints', np.int64(614)), ('convenience kits', np.int64(610)), ('ge healthcare', np.int64(586)), ('firm received', np.int64(573)), ('lot number', np.int64(525)), ('received reports', np.int64(513)), ('ethylene oxide', np.int64(492)), ('voluntary recall', np.int64(470)), ('product sterility', np.int64(466))]

Import FDA Problem Codes Dataset

In [43]:
foi_file = "/projectnb/sparkgrp/dd4g-muckrock-patient-safety/foiclass.txt"

In [44]:
product_codes = pd.read_csv(foi_file, sep="|", dtype=str, encoding="cp1252")

In [45]:
print(product_codes.head())
print(product_codes.columns)

  REVIEW_PANEL MEDICALSPECIALTY PRODUCTCODE  \
0           AN               AN         BRW
1           AN               AN         BRX
2           AN               AN         BRY
3           AN               AN         BSE
4           AN               AN         BSF

                             DEVICENAME DEVICECLASS UNCLASSIFIED_REASON  \
0                     Protector, Dental           1                 NaN
1                     Stool, Anesthesia           1                 NaN
2   Cabinet, Table And Tray, Anesthesia           1                 NaN
3  Analyzer, Gas, Helium, Gaseous-Phase           2                 NaN
4              Absorber, Carbon-Dioxide           1                 NaN

  GMPEXEMPTFLAG THIRDPARTYFLAG REVIEWCODE REGULATIONNUMBER SUBMISSION_TYPE_ID  \
0             N              N        NaN         868.5820                  4
1             N              N        NaN         868.6700                  4
2             N              N        NaN         868.6100                  4
3             N              Y        NaN         868.1640                  1
4             N              N        NaN         868.5310                  4

  DEFINITION PHYSICALSTATE TECHNICALMETHOD TARGETAREA Implant_Flag  \
0        NaN           NaN             NaN        NaN            N
1        NaN           NaN             NaN        NaN            N
2        NaN           NaN             NaN        NaN            N
3        NaN           NaN             NaN        NaN            N
4        NaN           NaN             NaN        NaN            N

  Life_Sustain_support_flag SummaryMalfunctionReporting
0                         N                    Eligible
1                         N                    Eligible
2                         N                    Eligible
3                         N                    Eligible
4                         N                    Eligible
Index(['REVIEW_PANEL', 'MEDICALSPECIALTY', 'PRODUCTCODE', 'DEVICENAME',
       'DEVICECLASS', 'UNCLASSIFIED_REASON', 'GMPEXEMPTFLAG', 'THIRDPARTYFLAG',
       'REVIEWCODE', 'REGULATIONNUMBER', 'SUBMISSION_TYPE_ID', 'DEFINITION',
       'PHYSICALSTATE', 'TECHNICALMETHOD', 'TARGETAREA', 'Implant_Flag',
       'Life_Sustain_support_flag', 'SummaryMalfunctionReporting'],
      dtype='object')

In [46]:
print(product_codes.columns)

Index(['REVIEW_PANEL', 'MEDICALSPECIALTY', 'PRODUCTCODE', 'DEVICENAME',
       'DEVICECLASS', 'UNCLASSIFIED_REASON', 'GMPEXEMPTFLAG', 'THIRDPARTYFLAG',
       'REVIEWCODE', 'REGULATIONNUMBER', 'SUBMISSION_TYPE_ID', 'DEFINITION',
       'PHYSICALSTATE', 'TECHNICALMETHOD', 'TARGETAREA', 'Implant_Flag',
       'Life_Sustain_support_flag', 'SummaryMalfunctionReporting'],
      dtype='object')

In [47]:
#product code is string
df['product_code'] = df['product_code'].astype(str)

#fda table is string
product_codes['PRODUCTCODE'] = product_codes['PRODUCTCODE'].astype(str)

#merged recall dataset
merged_df = df.merge(
    product_codes, 
    left_on='product_code', 
    right_on='PRODUCTCODE', 
    how='left'
)

#merged columns
print(merged_df[['product_code', 'product_description', 'DEVICENAME', 'DEVICECLASS']].head())

  product_code                                product_description  \
0          FNM  Adapt Pump, Model/Catalog Number: 61600200-Ada...
1          KPL              PIE PAK\nModels: P2HC-A, P2HC-S, P2HC
2         LFQO  Magnus Hybrid operating table columns 1180.01A...
3          RER  Raymond Laser alignment guide - Model #1096597...
4          KOG  PKG, OBTURATOR, 5.5MM FOR HASSON CANNULA, P/N ...

                                      DEVICENAME DEVICECLASS
0  Mattress, Air Flotation, Alternating Pressure           2
1                      Colonic Irrigation System           2
2                                            NaN         NaN
3                        Alignment Laser Product           N
4                                            NaN         NaN

In [48]:
print(merged_df.columns)
print(df.columns)

Index(['cfres_id', 'product_res_number', 'event_date_initiated',
       'event_date_posted', 'recall_status', 'res_event_number',
       'product_code', 'product_description', 'code_info', 'recalling_firm',
       'address_1', 'city', 'state', 'postal_code', 'additional_info_contact',
       'reason_for_recall', 'root_cause_description', 'action',
       'product_quantity', 'distribution_pattern', 'openfda.k_number',
       'openfda.registration_number', 'openfda.fei_number',
       'openfda.device_name', 'openfda.medical_specialty_description',
       'openfda.regulation_number', 'openfda.device_class', 'address_2',
       'event_date_terminated', 'firm_fei_number',
       'other_submission_description', 'k_numbers', 'pma_numbers',
       'event_date_created', 'openfda.pma_number', 'REVIEW_PANEL',
       'MEDICALSPECIALTY', 'PRODUCTCODE', 'DEVICENAME', 'DEVICECLASS',
       'UNCLASSIFIED_REASON', 'GMPEXEMPTFLAG', 'THIRDPARTYFLAG', 'REVIEWCODE',
       'REGULATIONNUMBER', 'SUBMISSION_TYPE_ID', 'DEFINITION', 'PHYSICALSTATE',
       'TECHNICALMETHOD', 'TARGETAREA', 'Implant_Flag',
       'Life_Sustain_support_flag', 'SummaryMalfunctionReporting'],
      dtype='object')
Index(['cfres_id', 'product_res_number', 'event_date_initiated',
       'event_date_posted', 'recall_status', 'res_event_number',
       'product_code', 'product_description', 'code_info', 'recalling_firm',
       'address_1', 'city', 'state', 'postal_code', 'additional_info_contact',
       'reason_for_recall', 'root_cause_description', 'action',
       'product_quantity', 'distribution_pattern', 'openfda.k_number',
       'openfda.registration_number', 'openfda.fei_number',
       'openfda.device_name', 'openfda.medical_specialty_description',
       'openfda.regulation_number', 'openfda.device_class', 'address_2',
       'event_date_terminated', 'firm_fei_number',
       'other_submission_description', 'k_numbers', 'pma_numbers',
       'event_date_created', 'openfda.pma_number'],
      dtype='object')

In [49]:
#turn device class field into strings 
merged_df['DEVICECLASS'] = merged_df['DEVICECLASS'].astype(str)

In [50]:
#check which product codes were not matched during merge 
unmatched = merged_df[merged_df['DEVICENAME'].isna()]['product_code'].unique()
print("Unmatched product codes:", unmatched)

Unmatched product codes: ['LFQO' 'KOG' 'N/A' '90LMA' '74DWF' 'nan' 'FRN--' 'rad' 'U28' 'CCH' 'BTE'
 'MPH' 'K--DD' 'dxg' 'NWR' 'LDT' 'ND' 'LNX' 'OWG' 'L22' 'NED' 'GBK' 'NA'
 '---' 'F' 'ndr' 'NPD' 'D' 'muj' 'cac' 'cck' 'NSX' 'MJQ' 'LNN' 'PRD' 'GBR'
 ':' 'KPF--' 'CAJ' 'LMO' 'DJR--' '74' 'FFK--' 'LNO' 'M' 'OGX' 'N/a' 'OYT'
 'MEW' 'NES' 'LXL' 'O-FY' 'H--NN' 'MFC' 'gkz' 'LDH' 'GAB--' 'JAJ' 'IZO--'
 'CGN--' 'LHI--' 'MKI' 'CEC--' 'DKJ--' 'JD-01' 'NFN' 'MDV' 'DS-22' 'EDI'
 'L--22' 'FSG' 'max' '80FMZ' 'PIU' 'JZL' 'J' 'NEP--' 'frn' 'KPS--' 'LID'
 'I--TI' 'CPK' 'SFB' 'ZZZ' 'NWD' 'EXEMP' 'FKX--' 'BBT' 'NCP' 'L' '79F'
 'LTK--' 'LPD' 'MPN--' 'CXT' 'EDH' 'GER' 'U--19' 'LLT' '-KPS' 'KPG'
 'GAA41' 'IZL--' 'NPN' 'LYW' 'KKX--' 'JQW--' 'HAP' 'ITF' '-JTC' '91' 'gbx'
 'LLC' 'OPU' 'LOS' 'ORO' 'GEL' 'LYB' '--' 'G-IO' 'GCB--' 'jjy' 'GKI'
 'KPR--' '-IYE' 'OMO' 'rce' 'DZi' 'LOR' 'LOM--' '6885' '74GBK' 'KMM' 'OOC'
 'BGK' '000' 'MXE' 'MFT' 'hpz' 'XLH' 'cbk' 'PNH' 'mkj' 'DIC--' 'MLM--'
 'LS-99' 'DS-21' 'NXS' 'lZE' 'PHI' 'MKJ--' 'OOM' 'lkv' 'LDQ']

In [51]:
#relevant cols 
keep_cols = ['cfres_id', 'product_code', 'product_description', 
             'reason_for_recall', 'DEVICENAME', 'DEVICECLASS']

#cleaned df
clean_df = merged_df[keep_cols].copy()

print(clean_df.head())
print(clean_df.columns)

  cfres_id product_code                                product_description  \
0   218307          FNM  Adapt Pump, Model/Catalog Number: 61600200-Ada...
1   218406          KPL              PIE PAK\nModels: P2HC-A, P2HC-S, P2HC
2   105069         LFQO  Magnus Hybrid operating table columns 1180.01A...
3   105700          RER  Raymond Laser alignment guide - Model #1096597...
4   131624          KOG  PKG, OBTURATOR, 5.5MM FOR HASSON CANNULA, P/N ...

                                   reason_for_recall  \
0  Agiliti identified an issue where the Adapt Pu...
1                             Lack of 510K clearance
2  A component of the Magnus hybrid OR system fai...
3  Raymond shipped a laser alignment guide as an ...
4  The parameters provided in the Laparoscopic Ma...

                                      DEVICENAME DEVICECLASS
0  Mattress, Air Flotation, Alternating Pressure           2
1                      Colonic Irrigation System           2
2                                            NaN         nan
3                        Alignment Laser Product           N
4                                            NaN         nan
Index(['cfres_id', 'product_code', 'product_description', 'reason_for_recall',
       'DEVICENAME', 'DEVICECLASS'],
      dtype='object')

In [52]:
clean_df.rename(columns={
    'DEVICENAME': 'device_name',
    'DEVICECLASS': 'device_class'
}, inplace=True)

print(clean_df.columns)

Index(['cfres_id', 'product_code', 'product_description', 'reason_for_recall',
       'device_name', 'device_class'],
      dtype='object')

In [54]:
clean_df['reason_for_recall'] = clean_df['reason_for_recall'].fillna("").str.lower()

In [55]:
problem_codes_file = "/projectnb/sparkgrp/dd4g-muckrock-patient-safety/extracted_problems/deviceproblemcodes.csv"
df_pc = pd.read_csv(problem_codes_file)

In [56]:
print(df_pc.head())
print(df_pc.columns)

   FDA_CODE                      TERM NCIT_CODE IMDRF_CODE
0         1     Old To Be Deactivated       NaN        NaN
1      1001   Failure To Run On AC/DC       NaN        NaN
2      1002                  Abnormal       NaN        NaN
3      1003                Absorption       NaN        NaN
4      1005  Measurements, inaccurate       NaN        NaN
Index(['FDA_CODE', 'TERM', 'NCIT_CODE', 'IMDRF_CODE'], dtype='object')

In [57]:
df_pc['FDA_CODE'] = df_pc['FDA_CODE'].astype(str)

In [58]:
df_pc['TERM'] = df_pc['TERM'].fillna("").str.lower()

In [59]:
recall_texts = clean_df['reason_for_recall'].tolist()
problem_terms = df_pc['TERM'].tolist()

all_text = recall_texts + problem_terms

In [60]:
vectorizer = TfidfVectorizer(stop_words='english')

tfidf_matrix = vectorizer.fit_transform(all_text)

In [61]:
recall_vectors = tfidf_matrix[:len(recall_texts)]
term_vectors = tfidf_matrix[len(recall_texts):]

In [62]:
similarity_matrix = cosine_similarity(recall_vectors, term_vectors)

In [63]:
#setting threshold, 0.40??? less preczse, more broad 

best_match_index = similarity_matrix.argmax(axis=1)
best_scores = similarity_matrix.max(axis=1)

threshold = 0.25

In [ ]:
best_scores[:20]

array([0.13571234, 0.27584258, 0.35678356, 0.10270102, 0.34994653,
       0.34994653, 0.34994653, 0.34994653, 0.34994653, 0.34994653,
       0.34994653, 0.34994653, 0.34994653, 0.34994653, 0.34994653,
       0.34994653, 0.34994653, 0.34994653, 0.34994653, 0.34994653])

In [64]:
best_match_index = similarity_matrix.argmax(axis=1)

clean_df['similarity_score'] = best_scores

clean_df['FDA_CODE'] = None
clean_df['TERM'] = None

mask = best_scores >= threshold

clean_df.loc[mask, 'FDA_CODE'] = df_pc.iloc[best_match_index[mask]]['FDA_CODE'].values
clean_df.loc[mask, 'TERM'] = df_pc.iloc[best_match_index[mask]]['TERM'].values

In [65]:
clean_df[['reason_for_recall','FDA_CODE','TERM']]

,reason_for_recall,FDA_CODE,TERM
0,agiliti identified an issue where the adapt pu...,None,None
1,lack of 510k clearance,4065,lack of effect
2,a component of the magnus hybrid or system fai...,1299,hybrid failure
3,raymond shipped a laser alignment guide as an ...,None,None
4,the parameters provided in the laparoscopic ma...,1142,failure to cycle
...,...,...,...
57506,philips has identified that in a limited numbe...,None,None
57507,access port system tray may develop cracks po...,None,None
57508,medline kits contain b. braun iv administratio...,None,None
57509,medline kits containing stryker's strykeflow 2...,None,None
57510,medline kits contain b. braun iv administratio...,None,None

In [66]:
#merges problem code dataset with recall txt - no cosine similarity, just appending extra info 
final_df = clean_df.merge(df_pc, on='FDA_CODE', how='left')

In [67]:
final_df = final_df.drop(columns=['TERM_x'])
final_df = final_df.rename(columns={'TERM_y':'problem_term'})

In [68]:
final_df['problem_term'].value_counts().head(20)

problem_term
sterility                       1013
device packaging compromised     570
expiration date error            519
performance                      409
port leak(s)                     308
screw head(s), incorrect         295
seal, incorrect                  293
shelf life exceeded              270
crack                            239
tube(s), defective               223
off-label use                    222
blood in tubing                  222
failure to cycle                 216
false negative result            215
reservoir                        214
air leak                         201
inadequate storage               200
moisture damage                  199
break                            191
no pressure                      181
Name: count, dtype: int64

In [73]:
final_df['problem_term'].unique()

array([nan, 'lack of effect', 'hybrid failure', 'failure to cycle',
       'radiation leak', 'human factors issue',
       'incorrect or inadequate test results',
       'locking mechanism failure', 'motor failure',
       'application network problem', 'malfunction',
       'grounding malfunction',
       'false reading from device non-compliance', 'failure to calibrate',
       'moisture damage', 'lead(s), burn(s) from', 'lead(s), shock from',
       'device packaging compromised', 'shielding failure',
       'valve(s), failure of', 'difficult to insert',
       'false positive result', 'failure to shut off',
       'filtration problem', 'safety interlock(s) inadequate',
       'probe failure', 'insulation failure', 'short fill',
       'unit inactivated', 'expiration date error',
       'solder joint fracture', 'laser output, unintended', 'mislabeled',
       'blood in tubing', 'sterility', 'battery failure', 'off-label use',
       'failure to conduct', 'normal', 'charging problem', 'reservoir',
       'cable break', 'missing information', 'break',
       'other (for use when an appropriate device code cannot be identified)',
       'migration', 'air leak', 'laser tip separation',
       'installation error', 'lens washers, failure of', 'flare or flash',
       'loose', 'suture line separation', 'crack', 'no pressure',
       'infusion or flow problem', 'film processing, inadequate',
       'incorrect interpretation of signal', 'screw head(s), incorrect',
       'surgical graft, failure of', 'failure to auto stop',
       'contamination', 'device contamination with biological material',
       'out-of-box failure', 'loose or intermittent connection',
       'monitor failure', 'failure to run on ac/dc', 'failure to pump',
       'device stenosis', 'adaptor, failure of', 'false negative result',
       'material rupture', 'occlusion within device', 'loss of power',
       'low test results', 'self-activation or keying',
       'lens, damaged by cartridge', 'separation failure',
       'no display/image', 'filling problem', 'hose line occlusion',
       'smoking', 'device fell', 'loss of data', 'device inoperable',
       'image orientation incorrect', 'filter', 'particulates',
       'dislodged', 'failure to power up', 'failure to eject',
       'low audible alarm', 'shock, electrical', 'hole in material',
       'false alarm', 'incorrect measurement', 'electrode(s), failure of',
       'aspiration issue', 'wireless communication problem',
       'inaccurate flow rate', 'repair', 'component missing',
       'incomplete or missing packaging', 'inaccurate synchronization',
       'needle, separation', 'volume accuracy problem',
       'failure to adhere or bond', 'difficult to flush',
       'monitor display alarm, failure of', 'source, incorrect',
       'failure to charge', 'air/gas in device',
       'operating system becomes nonfunctional', 'reaction',
       'application program problem: dose calculation error',
       'device issue', 'abnormal', 'unexpected color',
       'internal fixation, revision of', 'poor quality image',
       'unintended power up', 'difficult to position', 'collapse',
       'misassembly by users', 'disposable', 'low battery',
       'mechanical jam', 'table collapse', 'displacement',
       'laser pulse timing error', 'high readings',
       'cannula guide, needle insertion difficult',
       'wire(s), breakage of', 'fracture', 'foreign material',
       'excess flow or over-infusion', 'problem with sterilization',
       'failure to cut', 'fuse, blown',
       'microbial contamination of device', 'ph, low',
       'increased sensitivity', 'delayed charge time',
       'high test results', 'device damaged by another device',
       'device alarm system', 'complete loss of power',
       'alarm, failure of warning', 'performance', 'syringe, defective',
       'implant, removal of', 'split', 'difficult to remove',
       'failure to deliver', 'wrong label', 'poor visibility',
       'lens replacement', 'extra components',
       'device, or device fragments remain in patient',
       'alarm, error of warning', 'port leak(s)', 'failure to fire',
       'disassembly', 'unable to confirm conditions of use',
       'unintended movement', 'intermittent infusion', 'invalid sensing',
       'deflation problem', 'non-linear', 'failure to obtain sample',
       'pacing inadequately', 'misplacement', 'material deformation',
       'failure to form staple', 'inadequacy of device shape and/or size',
       'failure, intermittent', 'shaft break', 'high flux rate',
       'shelf life exceeded', 'alarm, audible',
       'deflation, cause unknown', 'tube(s), defective',
       'insulation degradation', 'low readings',
       'device contaminated at the user facility', 'unexpected shutdown',
       'unintended arm motion', 'packaging problem',
       'insulation, detached', 'device in backup-mode',
       'material fragmentation', 'lens, toric', 'aspiration, excessive',
       'electro-static discharge', 'cautery', 'material discolored',
       'material too rigid or stiff', 'arcing at paddles',
       'handpiece break', 'pressure sensor failure',
       'free or unrestricted flow', 'inflation problem',
       'valve(s), defective', 'drift', 'failure to capture',
       'compatibility', 'misassembled', 'erratic results',
       'seal, defective', 'no telemetry', 'dome collapse',
       'obstruction of flow', 'insufficient information',
       'device displays incorrect message',
       'issue with displayed error message', 'fluid/blood leak',
       'positioning failure', 'failure to zero',
       'tears, rips, holes in device, device material',
       'failure to disconnect', 'failure to seal', 'vacuum, loss of',
       'pallet crack(s)', 'failure to prime',
       'contamination of device ingredient or reagent',
       'reflux within device', 'emergency stop button or switch failure',
       'unstable', 'component falling', 'delivery system failure',
       'device operational issue', 'bicarbonate', 'lead(s), breakage of',
       'pumping stopped', 'failure to infuse', 'decreased sensitivity',
       'difficult to open or remove packaging material',
       'overheating of device', 'patient data problem',
       'defective device', 'labeling, missing', 'computer hardware error',
       'heat', 'no flow', 'alarm not visible', 'fail-safe design failure',
       'temperature problem', 'failure of device to self-test',
       'illegible information', 'material puncture/hole',
       'milliamps (ma) rate, unable to increase', 'overdelivery',
       'automatic injection system overinfusion', 'underdelivery',
       'hermetic seal, loss of', 'premature discharge of battery',
       'noise', 'output above specifications', 'calibration error',
       'failure to discharge', 'motion detector failure',
       'failure to clean adequately', 'biocompatibility',
       'program, failure to', 'incorrect device or component shipped',
       'inadequate instructions for healthcare professional',
       'blank screen', 'cable, defective', 'tip breakage',
       'incorrect error code', 'electrical shorting',
       'measurements, inaccurate', 'connection error',
       'blocked connection', 'gradient increase', 'failure to align',
       'firing problem', 'computer failure',
       'plunger not aligned properly', 'activation failure',
       'priming problem', 'close, difficult to',
       'difficult to open or close', 'inadequate storage', 'gel leak',
       'fitting problem', 'magnet failure', 'fail-safe problem',
       'resistance, loss of', 'transducer failure', 'balloon leak(s)',
       'device difficult to maintain', 'increased pump speed',
       'no device output', 'receiver stimulator unit, failure of',
       'incorrect, inadequate or imprecise result or readings',
       'corroded', 'failure to select signal', 'plunger override',
       'reverse osmosis', 'pacemaker found in back-up mode', 'no pacing',
       'unexpected therapeutic results', 'interference',
       'system fails to activate', 'deflation due to trauma',
       'balloon burst', 'arcing of electrodes',
       'unsealed device packaging', 'suction failure',
       'use of incorrect control/treatment settings',
       'alarm system, failure of check-catheter', 'lens, cloudy',
       'powder leak', 'circuit failure', 'shipping damage or problem',
       'filter tear(s)', 'light interference',
       'premature elective replacement indicator', 'structural problem',
       'wedge filter problem', 'seal, incorrect', 'sharp edges',
       'pumping problem', 'failure to transmit record', 'over-sensing',
       'cross reactivity', 'inappropriate waveform',
       'premature separation', 'shaft, split', 'component(s), broken',
       'backflow', 'defibrillation/stimulation problem',
       'side rails, failure of', 'damaged thread', 'altitude variations',
       'implant, repositioning of', 'unintended collision', 'bent',
       'tube(s), splitting of', 'mechanical problem', 'balloon pinhole',
       'lens (iol), defective, problem not specified',
       'device abrasion from instrument or another object',
       'program or algorithm execution failure', 'phantom problem',
       'conductivity', 'device contamination with body fluid',
       'adverse event without identified device or use problem',
       'detachment of device component', 'device reprocessing problem',
       'trocar failure', 'delamination', 'design/structure problem',
       'device disinfection or sterilization issue', 'failure to service',
       'failure to advance', 'electrical power problem',
       'optical problem', 'delivered as unsterile product',
       'membrane leak(s)', 'cuff degeneration', 'dull, blunt',
       'application security problem', 'electrical wires, defective',
       'therapy delivered to incorrect body area',
       'problem with software installation', 'aborted charge', 'escape',
       'electronic property issue', 'product quality problem',
       'insufficient cooling',
       'alarm system, failure of message-battery status',
       'unauthorized access to computer system', 'missing test results',
       'interrogation problem', 'excessive heating',
       'collimator design problem', 'unintended system motion',
       'channeling', 'material torqued', 'power problem',
       'battery charger, defective', 'leaflet fracture',
       'unintended magnet quench', 'disconnection', 'sticking',
       'sensing intermittently', 'increase in pressure', 'imprecision',
       'electrical overstress', 'table, tilting', 'alarm, no lead',
       'flammable', 'pressure, insufficient', 'inaccurate dispensing',
       'applicator failure', 'sensor problems',
       'device maintenance issue', 'implant breakage or physical damage',
       'magnetic interference', 'device expiration issue',
       'component incompatible', 'replace', 'programming issue',
       'shutter failure', 'battery problem: high impedance',
       'device unsafe to use in environment', 'failure to run on battery',
       'delayed alarm', 'failure to read input signal',
       'adhesive too strong',
       'device contaminated during manufacture or shipping',
       'strut fracture', 'suspect emi', 'inadequate lubrication',
       'improper alarm', 'antenna, failure of',
       'labelling, instructions for use or training problem',
       'gas delivery system failure', 'failure to deflate',
       'electromagnetic interference', 'method, improper/incorrect',
       'inadequate filtration process', 'filter leak(s)',
       'intermittent communication failure', 'hot oil leak',
       'percutaneous', 'mechanics altered', 'vibration',
       'material distortion', 'bolus mechanism failure',
       'lens (iol), migration of intraocular', 'material disintegration',
       'patient device interaction problem', 'optical discoloration',
       'failure to reset', 'energy spectrum incorrect', 'material frayed',
       'ventilation problem in device environment',
       'incorrect software programming calculations',
       'external fiberoptic break', 'false claim',
       'improper device output', 'low impedance',
       'fail-safe did not operate', 'visual prompts will not clear',
       'failure to deliver shock/stimulation', 'material perforation',
       'absorption', 'radiation output failure',
       'unstable capture threshold',
       'detachment of device or device component', 'degraded',
       'telemetry discrepancy', 'component(s), worn',
       'shoulder support, detachment of', 'entrapment of device',
       'device stops intermittently', 'loss of or failure to bond',
       'leak/splash', 'material twisted/bent', 'inaccurate delivery',
       'failure to fold', 'sparking', 'cool, failure to',
       'biofilm coating in device', 'markings, none',
       'coagulation in device or device ingredient',
       'shock, failure to advise', 'intermittent loss of power',
       'syringe markings, incorrectly placed',
       'pre or post-pumping problem', 'computer software problem',
       'overfill', 'decrease in pressure', 'defective component',
       'operating system version or upgrade problem', 'melted',
       'image display error/artifact', 'spring loading mechanism problem',
       'output problem', 'restricted flow rate', 'metal shedding debris',
       'material integrity problem', 'circuit breaker tripped',
       'tactile prompts/feedback', 'fungus in device environment',
       'unexpected/unintended radiation output', 'gas/air leak',
       'tidal volume fluctuations', 'cutoff point', 'kinked',
       'traditional use',
       'maintenance does not comply to manufacturers recommendations',
       'unclear information', 'folded',
       'lack of maintenance documentation or guidelines',
       'no fail-safe mechanism', 'inadequate user interface',
       'torn material', 'device remains implanted', 'chemical problem',
       'blood pooling', 'insufficient heating', 'inability to auto-fill',
       'interference with monitoring device', 'non reproducible results',
       'increase in suction', 'alarm, intermittent',
       'device appears to trigger rejection', 'failure to deliver energy',
       'folding issue', 'deterioration of prosthesis',
       'date/time-related software problem', 'material separation',
       'device handling problem', 'glass, shattered',
       'pocket stimulation', 'bubble(s)', 'lens, disc', 'endoleaks',
       'syringe, hole(s) in', 'output, high',
       'device packaging look-alike',
       'display or visual feedback problem', 'image resolution poor',
       'prophylactic removal due to corrective action',
       'application program problem: medication error',
       'application program version or upgrade problem',
       'delivery system issue, no description',
       'device markings/labelling problem', 'lockout mechanism failure',
       'lead(s), fracture of', 'component(s), overheating of',
       'intermittent shock/stimulation', 'protective measures problem',
       'use of device problem', 'failure to convert to back-up',
       'burst container or vessel', 'device damaged prior to use',
       'explosion', 'reuse', 'capturing problem',
       'tear, rip or hole in device packaging', 'transducer overheating',
       'failure to interrogate', 'device-device incompatibility',
       'human-device interface problem',
       'communication or transmission problem', 'device slipped',
       'loss of threshold', 'blood gas measurements, erroneous',
       'intermittent continuity', 'residue after decontamination',
       'emergency power failure', 'overcorrection',
       'inadequate instructions for non-healthcare professional',
       'stopcock valve, failure of', 'calibration problem',
       'missing value reason', 'cardiac enzyme evaluation, erroneous',
       'loosening of implant not related to bone-ingrowth',
       'device or device fragments location unknown',
       'fiberoptic break/separation', 'disengaged',
       'elective replacement', 'flushing problem', 'facilities issue',
       'failure to disinfect', 'inadequate or insufficient training',
       'application program problem', 'inadequate lighting',
       'transducer probe overheating',
       'problem with removal of enzymatic cleaner',
       'unintended electrical shock', 'chemical spillage',
       'battery problem', 'high impedance', 'old to be deactivated',
       'device remains activated',
       'key or button unresponsive/not working', 'failure to sense',
       'inaccurate information', 'retraction problem',
       'failure to analyze signal', 'ambient temperature problem',
       'improper flow or infusion', 'device emits odor',
       'suture line disruption', 'electromagnetic compatibility problem',
       'pierce',
       'application interface becomes non-functional or program exits abnormally',
       'explode', 'output, low', 'arcing', 'explanted',
       'thermal decomposition of device',
       'application program problem: power calculation error',
       'cross connection', 'dissection',
       'difficult or delayed activation',
       'manufacturing, packaging or shipping problem',
       'radio signal problem', 'device rinsing issue',
       'device, removal of (non-implant)', 'runaway',
       'intended use for traditional use',
       'premature end-of-life indicator', 'material protrusion/extrusion',
       'material too soft/flexible', 'coiled', 'uncoiled',
       'color variation, lens', 'data back-up problem',
       'material erosion', 'potentiometer readings, low',
       'couple, failure to',
       'error or warning message, failure to produce',
       'signal artifact/noise', 'fumes or vapors',
       'precipitate in device or device ingredient', 'misfire',
       'capacitative coupling', 'expulsion',
       'lens stuck in delivery system',
       'energy output to patient tissue incorrect',
       'interference with pacemaker', 'device tipped over',
       'cutter-torque-cable twisted or tangled', 'premature explantation',
       'changes in ambient temperature in device environment',
       'patient-device incompatibility', 'salt tablet(s), use of',
       'implant subsidence', 'strikethrough', 'pressure problem',
       'electro-magnetic interference (emi), compatibility/incompatibility',
       'difficult to advance', 'connection problem', 'r on t phenomenon',
       'device contamination with chemical or other material',
       'balloon rupture', 'fogging', 'stretched', 'occlusion, incorrect',
       'partial blockage', 'distilled water, contaminated',
       'unintended ejection', 'premature indicator activation',
       'function indicator light(s), failure of',
       'erratic or intermittent display', 'pipette, failure to aspirate',
       'lens (iol), scratch, mark on', 'radiation output problem',
       'lens, opacification of', 'physical resistance',
       'material opacification', 'low sensing threshold',
       'power conditioning problem', 'nonstandard device',
       'inadequate ultra filtration', 'material split, cut or torn',
       'battery impedance issue', 'display difficult to read',
       'inappropriate/inadequate shock/stimulation', 'high ph',
       'medical gas supply problem', 'fibrosis', 'accessory incompatible',
       'valve(s), sticking', 'ejection problem',
       'alarm system, failure of gas-leak/loss',
       'application program problem: parameter calculation error',
       'unintended head motion', 'image reversal',
       'inappropriate or unexpected reset', 'failure to convert rhythm',
       'clips, scissored', 'inadequate service', 'wrinkled',
       'respirator, detachment from', 'environmental particulates',
       'reset problem', 'installation-related problem',
       'hose line rupture', 'decrease in suction', 'extrusion',
       'device operates differently than expected', 'dent in material',
       'heat, failure to'], dtype=object)

In [70]:
clean_df['similarity_score'].describe()

count    57511.000000
mean         0.239033
std          0.121919
min          0.000000
25%          0.157825
50%          0.224107
75%          0.298726
max          1.000000
Name: similarity_score, dtype: float64

In [75]:
total = len(final_df)
matched = final_df['problem_term'].notna().sum()

print("Total recalls:", total)
print("Matched recalls:", matched)
print("Coverage:", matched / total)

Total recalls: 57511
Matched recalls: 23049
Coverage: 0.40077550381666116

In [88]:
final_df['problem_term'].value_counts().head(15)

problem_term
sterility                       1013
device packaging compromised     570
expiration date error            519
performance                      409
port leak(s)                     308
screw head(s), incorrect         295
seal, incorrect                  293
shelf life exceeded              270
crack                            239
tube(s), defective               223
off-label use                    222
blood in tubing                  222
failure to cycle                 216
false negative result            215
reservoir                        214
Name: count, dtype: int64

In [82]:
final_df

,cfres_id,product_code,product_description,reason_for_recall,device_name,device_class,similarity_score,FDA_CODE,problem_term,NCIT_CODE,IMDRF_CODE
0,218307,FNM,"Adapt Pump, Model/Catalog Number: 61600200-Ada...",agiliti identified an issue where the adapt pu...,"Mattress, Air Flotation, Alternating Pressure",2,0.135712,None,NaN,NaN,NaN
1,218406,KPL,"PIE PAK\nModels: P2HC-A, P2HC-S, P2HC",lack of 510k clearance,Colonic Irrigation System,2,0.275843,4065,lack of effect,C187247,A0105
2,105069,LFQO,Magnus Hybrid operating table columns 1180.01A...,a component of the magnus hybrid or system fai...,NaN,nan,0.356784,1299,hybrid failure,NaN,NaN
3,105700,RER,Raymond Laser alignment guide - Model #1096597...,raymond shipped a laser alignment guide as an ...,Alignment Laser Product,N,0.102701,None,NaN,NaN,NaN
4,131624,KOG,"PKG, OBTURATOR, 5.5MM FOR HASSON CANNULA, P/N ...",the parameters provided in the laparoscopic ma...,NaN,nan,0.349947,1142,failure to cycle,C63187,A050703
...,...,...,...,...,...,...,...,...,...,...,...
57506,217626,OWB,Product Name: Allura Xper FD10C;\nModel number...,philips has identified that in a limited numbe...,Interventional Fluoroscopic X-Ray System,2,0.203881,None,NaN,NaN,NaN
57507,217850,NAY,"da Vinci SP, SP Access Port Kit, Large Incisi...",access port system tray may develop cracks po...,"System, Surgical, Computer Controlled Instrument",2,0.245580,None,NaN,NaN,NaN
57508,217742,OJG,Medline Kits containing B. Braun IV Administra...,medline kits contain b. braun iv administratio...,Neurological Tray,1,0.148730,None,NaN,NaN,NaN
57509,217876,FDE,Medline medical procedure convenience kits lab...,medline kits containing stryker's strykeflow 2...,Laparoscopy Kit,2,0.243951,None,NaN,NaN,NaN
57510,217732,CAI,Medline Kits containing B. Braun IV Administra...,medline kits contain b. braun iv administratio...,"Circuit, Breathing (W Connector, Adaptor, Y Pi...",1,0.148730,None,NaN,NaN,NaN

In [87]:
final_df[['cfres_id','reason_for_recall','FDA_CODE','problem_term']].sample(20)

,cfres_id,reason_for_recall,FDA_CODE,problem_term
23475,110836,distal part of the anchor may break on inserti...,1069,break
13104,111751,there is potential for the sterility of the pr...,1595,sterility
24331,67897,slow deflation or no deflation,1149,deflation problem
35955,95190,there is a potential for delamination in one l...,2904,delamination
25954,140891,user settings were no longer on the monitor's ...,1407,monitor failure
32843,162149,this correction is being initiated based on a ...,None,NaN
44424,204519,masks non-invasive interface for channeling ai...,None,NaN
15274,174503,the protective material used in the manufactur...,None,NaN
53583,51504,unintended gantry movements : ge healthcare ha...,None,NaN
49211,160233,the locking punch guide was not sufficiently g...,None,NaN
53956,116502,possibility that the inner pouch may be compro...,None,NaN
45942,200814,reports of disconnection of the 15mm connector...,2299,"tube(s), defective"
9073,179172,there is the potential for various failures wi...,1534,"resistance, loss of"
53075,66344,sterility (package integrity) compromised: the...,2916,device packaging compromised
1578,25202,the tip of the stiffened cannula might break d...,1069,break
20452,187506,there is a potential for flaking metal and/or ...,None,NaN
29779,102395,carl zeiss meditec received a report that the ...,None,NaN
14237,133395,the labelled expiration dating of the affected...,1595,sterility
41367,83747,raw material supplied by a third party used to...,None,NaN
16438,198206,product did not meet shelf-life testing requir...,1567,shelf life exceeded